version: "3.8"

services:
  app:
    container_name: workspace
    build: 
      context: .
      dockerfile: Dockerfile-tomcat
    environment:
      - TZ=Asia/Seoul
    ports:
      - 9999:8080
    depends_on:
      - database
  
  database:
    container_name: workspace-db
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: docker-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: workspace
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111
